# Copyright (c) 2026 7-Sol. All rights reserved.
apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: log-receiver-pipeline
description: Delivery pipeline for Log Ingestion Server
serialPipeline:
  stages:
    - targetId: beta
      profiles: [beta]
    - targetId: prod
      profiles: [prod]
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: beta
description: Beta environment
gke:
  cluster: projects/servers-7-sol/locations/northamerica-northeast1/clusters/autopilot-cluster
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production environment
gke:
  cluster: projects/servers-7-sol/locations/northamerica-northeast1/clusters/autopilot-cluster
