# Copyright (c) 2026 7-Sol. All rights reserved.

# Server Configuration
server.port=8080
server.shutdown=graceful

# Management Configuration
management.server.port=8081
management.endpoints.web.exposure.include=health,prometheus,loggers
management.endpoint.health.show-details=always

# MongoDB Configuration
# We rely on SPRING_MONGODB_USERNAME and SPRING_MONGODB_PASSWORD
# environment variables for authentication, which are mapped in the Helm chart.
spring.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/logger}

# NATS Configuration
app.nats.uri=${NATS_URI:nats://localhost:4222}

# Logging Retention
# (Mappings now directly use environment variables in Java code)
