# Copyright (c) 2026 7-Sol. All rights reserved.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-receiver.fullname" . }}
  labels:
    {{- include "log-receiver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "log-receiver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "log-receiver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8081
              protocol: TCP
          env:
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.mongoUriFromConfig }}
                  key: {{ .Values.env.mongoUriKey }}
            - name: SPRING_MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.mongoUserFromConfig }}
                  key: {{ .Values.env.mongoUserKey }}
            - name: SPRING_MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.env.mongoPasswordFromSecret }}
                  key: {{ .Values.env.mongoPasswordKey }}
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.natsUrlFromConfig }}
                  key: {{ .Values.env.natsUrlKey }}
            - name: NATS_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.natsSubjectFromConfig }}
                  key: {{ .Values.env.natsSubjectKey }}
            - name: APP_LOGGING_RETENTION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.env.retentionDaysFromConfig }}
                  key: {{ .Values.env.retentionDaysKey }}
          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
