# Copyright (c) 2026 7-Sol. All rights reserved.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "log-receiver.fullname" . }}
  labels:
    {{- include "log-receiver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "log-receiver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "log-receiver.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: management
              containerPort: 8081
              protocol: TCP
          env:
            # Config for Mongo settings
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.mongo }}
                  key:  {{ .Values.app.confKeys.mongoDb }}
            - name: REPLICA_SET
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.mongo }}
                  key:  {{ .Values.app.confKeys.mongoRs }}
            - name: MONGO_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.mongo }}
                  key:  {{ .Values.app.confKeys.mongoHosts }}
            - name: MONGO_AIS_USER
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.mongo }}
                  key:  {{ .Values.app.confKeys.mongoUser }}
            - name: MONGO_AUTO_INDEX_CREATE
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.mongo }}
                  key:  {{ .Values.app.confKeys.mongoAutoIndex }}
                  optional: true
            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.nats  }}
                  key:  {{ .Values.app.confKeys.natsUrl }}
            - name: NATS_LOG_SUBJECT
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.nats }}
                  key:  {{ .Values.app.confKeys.natsLogSubject }}
                  optional: true
            - name: APP_LOGGING_RETENTION_DAYS
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.app.configs.mongo }}
                  key:  {{ .Values.app.confKeys.logRetentionDays }}
                  optional: true

            # Secrets pulled from Kubernetes Secrets
            - name: MONGODB_AIS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.app.secrets.mongodbSecret }}
                  key:  {{ .Values.app.secretKeys.mongoPassword }}

          startupProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
            failureThreshold: 30
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: management
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: management
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
